FROM node:20-alpine3.17
WORKDIR /grabtern-app
COPY ./package*.json ./
RUN npm install
# Copy the rest of the application code
COPY . .
# Expose the port your application listens on (if applicable)
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]