name: Greetings

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Determine Actor Type
        id: determine_actor_type
        run: |
          actor_type=""
          if [[ "${{ github.actor }}" == "${{ github.repository_owner }}" ]]; then
            actor_type="collaborator"
          else
            actor_type="contributor"
          fi
          echo "::set-output name=actor_type::$actor_type"

      - name: Greet Actor
        id: greet_actor
        run: |
          actor_type="${{ steps.determine_actor_type.outputs.actor_type }}"
          if [[ "${{ github.actor }}" != "dependabot[bot]" ]]; then
            case $actor_type in
              "contributor")
                echo "Hello ${{ github.actor }}, thanks for your contribution! Your effort is highly appreciated."
                ;;
              "collaborator")
                echo "Welcome ${{ github.actor }}! We appreciate your continued collaboration on this project."
                ;;
              *)
                echo "Hello ${{ github.actor }}! Thank you for your interaction with this repository."
                ;;
            esac
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on Issue
        if: ${{ github.event_name == 'issues' }}
        run: |
          actor_type="${{ steps.determine_actor_type.outputs.actor_type }}"
          issue_message=""
          if [[ "${{ github.actor }}" != "dependabot[bot]" ]]; then
            case $actor_type in
              "contributor")
                issue_message="Hello ${{ github.actor }}, thanks for opening an issue! Your contribution is valuable to us. The maintainers will review this issue and provide feedback as soon as possible."
                ;;
              *)
                issue_message="Hello ${{ github.actor }}! Thank you for your interaction with this repository. We have noted your issue."
                ;;
            esac
            echo "Issue Comment: $issue_message"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on Pull Request
        if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          actor_type="${{ steps.determine_actor_type.outputs.actor_type }}"
          pr_message=""
          if [[ "${{ github.actor }}" != "dependabot[bot]" ]]; then
            case $actor_type in
              "contributor")
                pr_message="Hello ${{ github.actor }}, thanks for raising a pull request! Your contribution is valuable to us. The maintainers will review this pull request and provide feedback as soon as possible. Keep up the great work!"
                ;;
              *)
                pr_message="Hello ${{ github.actor }}! Thank you for your interaction with this repository. We have noted your pull request."
                ;;
            esac
            echo "Pull Request Comment: $pr_message"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
